# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Invariante
tagline:          'Algumas coisas nunca mudam'
description:      'Escrito por <a href="https://twitter.com/brunokoga">Bruno</a> e <a href="https://twitter.com/diogot">Diogo</a>.' 
url:              http://invariante.com
baseurl:          ''
author:
  name: Bruno Koga e Diogo Tridapalli
  email: feed@invariante.com

paginate:         5

github:
  repo:           https://github.com/appsterdambr/invariante
