# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Invariante
tagline:          'Algumas coisas nunca mudam'
description:      'Escrito por <a href="https://twitter.com/brunokoga">Bruno</a> e <a href="https://twitter.com/diogot">Diogo</a>.' 
url:              http://invariante.com
baseurl:          http://brasil.appsterdam.rs/invariante

paginate:         5

github:
  repo:           https://github.com/appsterdambr/invariante
